from .coarse_registration import coarse_registration
from .rigid_registration import rigid_registration
from .affine_registration import affine_registration
from .composite_registration import composite_registration